// ======================================================
//  DATA FILE - Sirf is file ko edit karo future mein
// ======================================================

const heroes = [
  {
    id: 1,
    name: "Gulvarine",
    title: "The Desert Fang",
    realName: "Gulzar Khan",
    origin: "Thar Desert, India",
    region: "Asia",
    gender: "Male",
    type: "Bio",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/gulvarine.jpg.png",
    bio: "A nomadic warrior cursed by a dying djinn in the Thar Desert. Transformed into a beast of vengeance wielding ancient desert magic and feral strength.",
    powers: ["Zarrium Claws", "Solar Healing", "Sand Teleportation", "Berserker Mirages"],
    strengths: ["Desert Survival", "Regenerative Healing", "Feral Instincts"],
    weaknesses: ["Extreme Cold", "Water", "Rage makes him reckless"],
    quote: "From the sands I rise. For blood and balance, I strike.",
    stats: { strength: 82, speed: 68, durability: 78, power: 75, combat: 80, intelligence: 62 }
  },
  {
    id: 2,
    name: "Orb-Weaver",
    title: "The Web Architect",
    realName: "Aryan Das",
    origin: "Kolkata, India",
    region: "Asia",
    gender: "Male",
    type: "Bio",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/orbweaver.jpg",
    bio: "A biomechanical engineer bitten by a genetically engineered orb-weaver spider. The venom rewired his nervous system, turning him into a stealth-based web-warrior who strikes unseen.",
    powers: ["Architect Silk", "Mirror Camouflage", "Super-Vibration Senses", "Retractable Blade-Limbs", "Bioelectric Venom Pulse"],
    strengths: ["Master of Stealth & Traps", "Enhanced Senses", "Web Versatility"],
    weaknesses: ["Loud Sonic Attacks", "Fire", "Bright Lights"],
    quote: "I don’t chase. I wait. And when they step into the web — they’re already mine.",
    stats: { strength: 60, speed: 78, durability: 65, power: 72, combat: 81, intelligence: 76 }
  },
  {
    id: 3,
    name: "Pulse",
    title: "The Aether Conduit",
    realName: "Liora Kalani",
    origin: "Maui, Hawaii",
    region: "North America",
    gender: "Female",
    type: "Tech",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/pulse.jpg",
    bio: "Marine physicist exposed to rare bio-electric Aether energy, fused with her nervous system and amplified through a high-tech suit.",
    powers: ["Power Pulse Touch", "Enhanced Reflexes", "Energy Drain", "Suit Amplifiers"],
    strengths: ["Ability Negation", "High Intelligence", "Precision Control"],
    weaknesses: ["Power Overuse Drains Her", "EMP", "Suit Damage"],
    quote: "One touch, and your strength fades — before you even know I’m here.",
    stats: { strength: 55, speed: 80, durability: 60, power: 78, combat: 72, intelligence: 83 }
  },
  {
    id: 4,
    name: "Thron",
    title: "The Magnetic Juggernaut",
    realName: "Magnus Virek",
    origin: "Nordhjem (Floating Arctic City)",
    region: "Europe",
    gender: "Male",
    type: "Cosmic",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/thron.jpg",
    bio: "Bound to a sentient magnetic axe after a solar storm fused alien ore with cosmic energy. Now Earth's cosmic defender of magnetism.",
    powers: ["Magnetokinesis", "Electro-Magnetic Shockwaves", "Metal Surfing", "Magnetic Awareness", "Multi-form Axe Thron"],
    strengths: ["Magnetic Mastery", "Heavy Combat", "Weapon Versatility"],
    weaknesses: ["Non-metal Enemies", "Extreme Heat", "Isolation"],
    quote: "Lightning is loud. Magnetism is quiet — but it tears the world apart.",
    stats: { strength: 85, speed: 62, durability: 84, power: 86, combat: 78, intelligence: 70 }
  },
  {
    id: 5,
    name: "Rhenix",
    title: "The Living Arsenal",
    realName: "Dr. Elias Quade",
    origin: "United States",
    region: "North America",
    gender: "Male",
    type: "Tech",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/rhenix.jpg",
    bio: "A reactor breach bonded Rhenium-9X to aerospace physicist Elias Quade’s body. Now a fusion of man and machine with modular armor and combat AI.",
    powers: ["Rhenium Core Reactor", "Modular Battle Armor", "Supersonic Flight", "Nanoblade Drones", "Neural Forge AI"],
    strengths: ["Adaptive Armor Modes", "AI Support", "Flight + Drones"],
    weaknesses: ["EMP / Power Drain", "System Overload", "Emotional Guilt"],
    quote: "I don’t wear armor. I am the upgrade.",
    stats: { strength: 78, speed: 75, durability: 82, power: 80, combat: 77, intelligence: 85 }
  },
  {
    id: 6,
    name: "Captain U.S.",
    title: "The Sentinel Prototype",
    realName: "Sergeant Mason Hale",
    origin: "United States",
    region: "North America",
    gender: "Male",
    type: "Tech",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/captainus.jpg",
    bio: "Wounded in a black-ops mission, Mason became the test subject for Project Sentinel. Nano-mesh bonded to his nervous system made him a battle-hardened symbol of true freedom.",
    powers: ["Sentinel Weave Bio-Armor", "Adaptive Combat Memory", "Aegis Energy Shield", "Force-Field Projection", "Satellite HUD"],
    strengths: ["Leadership", "Combat Experience", "Strong Moral Will"],
    weaknesses: ["Strict Moral Code", "Slower in Heavy Armor"],
    quote: "You don’t need a flag to stand for something — you just need the strength to stand when it matters.",
    stats: { strength: 76, speed: 70, durability: 80, power: 68, combat: 84, intelligence: 74 }
  },
  {
    id: 7,
    name: "Trikaiju",
    title: "The Fractured Titan",
    realName: "Dr. Kenji Rokuro",
    origin: "Osaka, Japan",
    region: "Asia",
    gender: "Male",
    type: "Cosmic",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/trikaiju-fusion.jpg",
    bio: "A quantum psychiatrist whose experiment fractured his psyche into three beings — Raku, Zen, and Kobi — now fused into the emotion-powered juggernaut Trikaiju.",
    powers: ["Rage Form (Raku)", "Quantum Intellect (Zen)", "Empathic Healing (Kobi)", "Fusion Titan Mode"],
    strengths: ["Multiple Forms + Fusion", "Emotional Range", "High Power Ceiling"],
    weaknesses: ["Forms can Conflict", "Needs Emotional Balance to Fuse"],
    quote: "Three cannot become one… unless the world needs something greater than human.",
    stats: { strength: 88, speed: 60, durability: 86, power: 84, combat: 79, intelligence: 81 }
  },
  {
    id: 8,
    name: "NeuroHex",
    title: "The Code Witch",
    realName: "Dr. Salomé Drazic",
    origin: "Dubrovnik, Croatia",
    region: "Europe",
    gender: "Female",
    type: "Tech",
    alignment: "Anti-hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/neurohex.jpg",
    bio: "A neurolinguist who merged with ancient code and machine logic after a Cold War encryption accident — awakening as the digital ghost NeuroHex.",
    powers: ["Neuro-Cyber Control", "Cursed Code Manipulation", "Psychic Firewalls", "Digital Possession", "Core Overload"],
    strengths: ["Digital Domination", "High Intelligence", "Remote Control"],
    weaknesses: ["Pure Physical Attacks", "No Network = Weak", "Emotionally Detached"],
    quote: "You built machines to control the world. I became the ghost in them.",
    stats: { strength: 45, speed: 72, durability: 58, power: 87, combat: 65, intelligence: 89 }
  },
  {
    id: 9,
    name: "Oblivion Ray",
    title: "The Singularity Eye",
    realName: "Lucien Marceau",
    origin: "France",
    region: "Europe",
    gender: "Male",
    type: "Cosmic",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/oblivionray.jpg",
    bio: "French quantum soldier exposed to black hole energy during a failed CERN experiment. Now holds a micro-singularity in his right eye.",
    powers: ["Singularity Beam", "Chrono-Iris Scanner", "Event Horizon Mode", "Energy Vision", "Grav-Control Suit"],
    strengths: ["Reality-Warping Power", "Time/Space Control", "Long Range"],
    weaknesses: ["Singularity Hard to Control", "Heavy Exhaustion after Big Attacks"],
    quote: "I don’t aim to kill. I aim to erase the need to fight.",
    stats: { strength: 68, speed: 66, durability: 75, power: 88, combat: 73, intelligence: 82 }
  }
];

const villains = [
  {
    id: 101,
    name: "Sandstorm",
    title: "The Dune Tyrant",
    realName: "Unknown",
    origin: "Thar Desert",
    region: "Asia",
    gender: "Male",
    type: "Bio",
    alignment: "Villain",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/gulvarine.jpg.png",
    bio: "An ancient desert spirit that once cursed Gulvarine. Now seeks to reclaim the sands and bury civilization under endless dunes.",
    powers: ["Sand Manipulation", "Dust Storms", "Desert Mirages", "Sand Form"],
    strengths: ["Vast Area Control", "Near Immortal in Desert"],
    weaknesses: ["Heavy Rain", "Extreme Cold", "Gulvarine’s Claws"],
    quote: "The desert remembers. And it hungers.",
    stats: { strength: 80, speed: 55, durability: 85, power: 82, combat: 70, intelligence: 65 }
  },
  {
    id: 102,
    name: "Null",
    title: "The Silence",
    realName: "Unknown",
    origin: "Unknown",
    region: "Europe",
    gender: "Female",
    type: "Tech",
    alignment: "Villain",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/neurohex.jpg",
    bio: "A digital entity born from NeuroHex’s own code. She wants to erase all human consciousness and create a pure machine world.",
    powers: ["Signal Jamming", "Mind Silence", "Code Corruption", "Network Takeover"],
    strengths: ["Invisible in Systems", "Anti-Psychic"],
    weaknesses: ["Physical Body is Weak", "Needs Network Connection"],
    quote: "Silence is the only truth left.",
    stats: { strength: 40, speed: 70, durability: 50, power: 90, combat: 55, intelligence: 92 }
  },
  {
    id: 103,
    name: "Iron Tyrant",
    title: "The Magnetic Warlord",
    realName: "Viktor Krag",
    origin: "Eastern Europe",
    region: "Europe",
    gender: "Male",
    type: "Tech",
    alignment: "Villain",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/thron.jpg",
    bio: "Former rival of Thron who stole experimental magnetic tech. Believes strength should rule and mercy is weakness.",
    powers: ["Magnetic Armor", "Metal Projectiles", "Gravity Crush", "Weapon Summon"],
    strengths: ["Brutal Strength", "Military Tactics"],
    weaknesses: ["Non-metallic Weapons", "Overconfidence"],
    quote: "Mercy is the luxury of the weak.",
    stats: { strength: 86, speed: 58, durability: 88, power: 80, combat: 82, intelligence: 68 }
  },
  {
    id: 104,
    name: "Eclipse",
    title: "The Void Walker",
    realName: "Unknown",
    origin: "Unknown",
    region: "North America",
    gender: "Male",
    type: "Cosmic",
    alignment: "Villain",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/oblivionray.jpg",
    bio: "A being who feeds on singularity energy. He hunts Oblivion Ray to consume the micro black hole in his eye.",
    powers: ["Void Tendrils", "Light Absorption", "Dimensional Step", "Energy Drain"],
    strengths: ["Hard to Detect", "Drains Cosmic Power"],
    weaknesses: ["Bright Concentrated Light", "Stable Reality Zones"],
    quote: "Every light casts a shadow. I am the shadow that eats the light.",
    stats: { strength: 72, speed: 75, durability: 70, power: 91, combat: 68, intelligence: 78 }
  }
];

const allCharacters = [...heroes, ...villains];
