// ======================================================
//  DATA FILE - Sirf is file ko edit karo future mein
// ======================================================
// Naya hero/villain add karne ke liye neeche wale format mein copy-paste karo
// Image GitHub pe upload karke full link yahan daal dena

const heroes = [
  {
    id: 1,
    name: "Gulvarine",
    title: "The Desert Fang",
    realName: "Gulzar Khan",
    origin: "Thar Desert, India",
    region: "Asia",
    gender: "Male",
    type: "Bio",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/gulvarine.jpg.png",
    bio: "A nomadic warrior cursed by a dying djinn in the Thar Desert. Transformed into a beast of vengeance wielding ancient desert magic and feral strength.",
    powers: ["Zarrium Claws", "Solar Healing", "Sand Teleportation", "Berserker Mirages"],
    quote: "From the sands I rise. For blood and balance, I strike.",
    stats: { strength: 82, speed: 68, durability: 78, power: 75, combat: 80, intelligence: 62 }
  },
  {
    id: 2,
    name: "Orb-Weaver",
    title: "The Web Architect",
    realName: "Aryan Das",
    origin: "Kolkata, India",
    region: "Asia",
    gender: "Male",
    type: "Bio",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/orbweaver.jpg",
    bio: "A biomechanical engineer bitten by a genetically engineered orb-weaver spider. The venom rewired his nervous system, turning him into a stealth-based web-warrior who strikes unseen.",
    powers: ["Architect Silk", "Mirror Camouflage", "Super-Vibration Senses", "Retractable Blade-Limbs", "Bioelectric Venom Pulse"],
    quote: "I don’t chase. I wait. And when they step into the web — they’re already mine.",
    stats: { strength: 60, speed: 78, durability: 65, power: 72, combat: 81, intelligence: 76 }
  },
  {
    id: 3,
    name: "Pulse",
    title: "The Aether Conduit",
    realName: "Liora Kalani",
    origin: "Maui, Hawaii",
    region: "North America",
    gender: "Female",
    type: "Tech",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/pulse.jpg",
    bio: "Marine physicist exposed to rare bio-electric Aether energy, fused with her nervous system and amplified through a high-tech suit.",
    powers: ["Power Pulse Touch", "Enhanced Reflexes", "Energy Drain", "Suit Amplifiers"],
    quote: "One touch, and your strength fades — before you even know I’m here.",
    stats: { strength: 55, speed: 80, durability: 60, power: 78, combat: 72, intelligence: 83 }
  },
  {
    id: 4,
    name: "Thron",
    title: "The Magnetic Juggernaut",
    realName: "Magnus Virek",
    origin: "Nordhjem (Floating Arctic City)",
    region: "Europe",
    gender: "Male",
    type: "Cosmic",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/thron.jpg",
    bio: "Bound to a sentient magnetic axe after a solar storm fused alien ore with cosmic energy. Now Earth's cosmic defender of magnetism.",
    powers: ["Magnetokinesis", "Electro-Magnetic Shockwaves", "Metal Surfing", "Magnetic Awareness", "Multi-form Axe Thron"],
    quote: "Lightning is loud. Magnetism is quiet — but it tears the world apart.",
    stats: { strength: 85, speed: 62, durability: 84, power: 86, combat: 78, intelligence: 70 }
  },
  {
    id: 5,
    name: "Rhenix",
    title: "The Living Arsenal",
    realName: "Dr. Elias Quade",
    origin: "United States",
    region: "North America",
    gender: "Male",
    type: "Tech",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/rhenix.jpg",
    bio: "A reactor breach bonded Rhenium-9X to aerospace physicist Elias Quade’s body. Now a fusion of man and machine with modular armor and combat AI.",
    powers: ["Rhenium Core Reactor", "Modular Battle Armor", "Supersonic Flight", "Nanoblade Drones", "Neural Forge AI"],
    quote: "I don’t wear armor. I am the upgrade.",
    stats: { strength: 78, speed: 75, durability: 82, power: 80, combat: 77, intelligence: 85 }
  },
  {
    id: 6,
    name: "Captain U.S.",
    title: "The Sentinel Prototype",
    realName: "Sergeant Mason Hale",
    origin: "United States",
    region: "North America",
    gender: "Male",
    type: "Tech",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/captainus.jpg",
    bio: "Wounded in a black-ops mission, Mason became the test subject for Project Sentinel. Nano-mesh bonded to his nervous system made him a battle-hardened symbol of true freedom.",
    powers: ["Sentinel Weave Bio-Armor", "Adaptive Combat Memory", "Aegis Energy Shield", "Force-Field Projection", "Satellite HUD"],
    quote: "You don’t need a flag to stand for something — you just need the strength to stand when it matters.",
    stats: { strength: 76, speed: 70, durability: 80, power: 68, combat: 84, intelligence: 74 }
  },
  {
    id: 7,
    name: "Trikaiju",
    title: "The Fractured Titan",
    realName: "Dr. Kenji Rokuro",
    origin: "Osaka, Japan",
    region: "Asia",
    gender: "Male",
    type: "Cosmic",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/trikaiju-fusion.jpg",
    bio: "A quantum psychiatrist whose experiment fractured his psyche into three beings — Raku, Zen, and Kobi — now fused into the emotion-powered juggernaut Trikaiju.",
    powers: ["Rage Form (Raku)", "Quantum Intellect (Zen)", "Empathic Healing (Kobi)", "Fusion Titan Mode"],
    quote: "Three cannot become one… unless the world needs something greater than human.",
    stats: { strength: 88, speed: 60, durability: 86, power: 84, combat: 79, intelligence: 81 }
  },
  {
    id: 8,
    name: "NeuroHex",
    title: "The Code Witch",
    realName: "Dr. Salomé Drazic",
    origin: "Dubrovnik, Croatia",
    region: "Europe",
    gender: "Female",
    type: "Tech",
    alignment: "Anti-hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/neurohex.jpg",
    bio: "A neurolinguist who merged with ancient code and machine logic after a Cold War encryption accident — awakening as the digital ghost NeuroHex.",
    powers: ["Neuro-Cyber Control", "Cursed Code Manipulation", "Psychic Firewalls", "Digital Possession", "Core Overload"],
    quote: "You built machines to control the world. I became the ghost in them.",
    stats: { strength: 45, speed: 72, durability: 58, power: 87, combat: 65, intelligence: 89 }
  },
  {
    id: 9,
    name: "Oblivion Ray",
    title: "The Singularity Eye",
    realName: "Lucien Marceau",
    origin: "France",
    region: "Europe",
    gender: "Male",
    type: "Cosmic",
    alignment: "Hero",
    image: "https://raw.githubusercontent.com/nitinja20/fake-super-hero-gallery/main/oblivionray.jpg",
    bio: "French quantum soldier exposed to black hole energy during a failed CERN experiment. Now holds a micro-singularity in his right eye.",
    powers: ["Singularity Beam", "Chrono-Iris Scanner", "Event Horizon Mode", "Energy Vision", "Grav-Control Suit"],
    quote: "I don’t aim to kill. I aim to erase the need to fight.",
    stats: { strength: 68, speed: 66, durability: 75, power: 88, combat: 73, intelligence: 82 }
  }
];

// Future mein Villains yahan add kar sakte ho
const villains = [];
